### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by averageflow** [averageflow/godmt#12]

**Comment by akshaybharambe14** [comment]
Hi, I can take this. 

It will be a great help if I get to know the specific implementation details. Is there anything that stops execution on windows?

**Comment by averageflow** [comment]
@akshaybharambe14 that is really nice to hear your will to contribute, both creating issues and with code :) i do not run windows in any machine and this cannot test this. 

My doubt is that I am not sure that using the `os.PathSeparator` in the several moments where we need to use `/` is enough to have windows compatibility with the paths. I am happy to hear your discoveries on this.

**Comment by akshaybharambe14** [comment]
If path is the only concern, then we can use `filepath` package to clean the path according to host/ target system.

I will open a PR for this.
