### ISSUE TITLE
Let users specify the output directory

### ISSUE THREAD

**Issue by akshaybharambe14** [averageflow/godmt#18]
**Is your feature request related to a problem? Please describe.**

The users may want to put the generated files to a desired directory. 

**Describe the solution you'd like**

A flag, preferably `-o=path/to/output/dir", can help.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by averageflow** [comment]
@akshaybharambe14 i find this is indeed a good addition to the program, and it can easily be added
