### ISSUE TITLE
When the json label is not given a syntax error occurs

### ISSUE THREAD

**Issue by lil5** [averageflow/godmt#9]
```go
type Example struct {
  ID string `uri:"id"`
}
```

for example this will generate:

```ts
export interface Example {
	"`uri:"id"`": string;
}
```

and should generate:

```ts
export interface Example {
	ID: string;
}
```

A the name should be used as a fallback for a json label.

---

Here is a happy flow with json label:

```go
type Example struct {
  ID string `json:"id"`
}
```

```ts
export interface Example {
	id: string;
}
```

**Comment by averageflow** [comment]
This is a good find @lil5 . I can see exactly where this issue happens, and i think the most common patterns should be parsed. 

Currently the tag gets turned to a name by the following order:
- JSON tag
- XML tag
- Fallback is the raw input of the tag

What must be done is an addition of the more common patterns, like `uri`, `form`, `db` and `mapstructure`. In case any of these things are available then an empty string should be returned, which will trigger other functions to use the “name”, such as when you use the preserve flag.
